### ISSUE TITLE
Something about IPO

### ISSUE THREAD

**Issue by stvsd1314** [PKU-MARL/Safe-Policy-Optimization#23]
Hello, thanks for your excellent work. For the IPO algorithm, I wonder that if it is suit for the environment whose action space is discrete?
Because of that the interior point algorithm is not suit for the optimization problem whose decisision is discrete.

**Comment by zmsn-2077** [comment]
Indeed, it is accurate that all of SafePO's current algorithms solely accommodate continuous space. However, in terms of utilizing an interior point method in the context of discrete space, we suggest consulting the referenced video for further guidance. I have done very little research on this topic. 


1. Aaron Sidford: Introduction to interior point methods for discrete optimization, lecture II. https://www.youtube.com/watch?v=ivTi_mnMNxw

Our team loves sharing and open-source. We also strongly desire your utilization of our other two algorithmic libraries and environments, specifically tailored toward constrained optimization and safe reinforcement learning. 

2. Safety-Gymnasium. https://github.com/OmniSafeAI/safety-gymnasium
3. OmniSafe. https://github.com/OmniSafeAI/omnisafe

**Comment by stvsd1314** [comment]
Thanks for your replay! By the way, I wonder that why not use the p(a|s)*violation_cost(s,a) to calculate the Expectation of violation cost in your IPO algorithm. And what is the purpose of the function "update_cost_net" in learning process. Can your share some references for this algorithm that you write? Thanks again.

**Comment by stvsd1314** [comment]
Thanks for your response! By the way, I wonder that what is the mean of " penalty = self.kappa / (c + 1e-8)" the policy loss calculating of IPO？ Shouldn't it be in the form of a log like the equation given in the original paper?

**Comment by zmsn-2077** [comment]
For more details, you can refer to https://github.com/OmniSafeAI/omnisafe/issues/223. 
Feel free to ask to reopen this if you have more questions.
